### ISSUE TITLE
Creation of request from AuthRequest fails on UWP

### ISSUE THREAD

**Issue by cherepets** [renber/SeafClient#3]
GetCustomizedRequest method returns null.
POST request would work crossplatform.
Suggested changes are added to pull request.
https://github.com/renber/SeafClient/pull/2

**Comment by renber** [comment]
Thanks for your efforts. Unfortunately, changing the authentication request to post and passign the password as string will leak the password in memory after the request has been sent. That's why the original source uses a char[] array (since SecureString is not available on all platforms) and a custom request.

But I'll look into the issue to find a different solution.

**Comment by renber** [comment]
AuthRequest and CredentialFormContent have been fixed to work under UWP without storing the password as string (see d4c4c53d2aca629de565fc71ec453a8a61bc84c9)
