### ISSUE TITLE
Add Timeout to Etablish and SendRequestAsync

### ISSUE THREAD

**Issue by uPloraX** [renber/SeafClient#8]
Could you add a timout to atleast the `Etablish` method?
I would implement it like this, but don't know in which style you want to have it:

    public async Task<T> SendRequestAsync<T>(Uri serverUri, SeafRequest<T> request, double timeoutSeconds = 10)
    {            
        var requestMessage = CreateHttpRequestMessage(serverUri, request);

        HttpResponseMessage response;
        var handler = new HttpClientHandler { AllowAutoRedirect = false };
        var tokenSource = new CancellationTokenSource(TimeSpan.FromSeconds(timeoutSeconds));

        using (var client = new HttpClient(handler))   
            response = await client.SendAsync(requestMessage, tokenSource.Token);                            

        if (request.WasSuccessful(response))
            return await request.ParseResponseAsync(response);

        throw new SeafException(request.GetSeafError(response));
    }

This won't break any method using it and would easily allow to add a timeout to any using it.
Thoughts?

PS: Your code overall is a bit inconsistent (e.g. only sometimes `var`, `string / String` there, missing/wrong doc), if you want I could take time to clear it a bit up (with ReSharper too).

**Comment by renber** [comment]
The easiest way would be to just pass a custom ISeafWebConnection when establishing a SeafSession which implements a timeout (e.g. through a Property). For the timeout I'd directly use a TimeSpan which removes confusion about the time unit. This could also be incorporated into the default SeafHttpConnection, so that you can a custom timeout when you instantiate it yourself.

I do not know whether it would be wise to add a specific timeout parameter to all SeafSession methods since the interface would become somehow "polluted". Furthermore, we cannot be sure that all ISeafWebConnections support timeouts anyway.
The [default timeout  for HttpClientHandler](https://msdn.microsoft.com/en-us/library/system.net.http.httpclient.timeout(v=vs.110).aspx)  is 100 seconds. Maybe this could be initialized to a more sensible value in the default implemenation. Maybe 10 seconds?

Please feel free to clean the code and complete the comments, respectively. I'll gladly incorporate any pull requests related to code quality.

**Comment by uPloraX** [comment]
I can basically implement the same implementation with the cancellation token, but I came across the next problem.. when uploading a file, I would like also to be able to cancel the upload.
Also when I upload a file with like 2-3GB and set the max download size higher in seafile config, it will upload it correctly but throws an TaskCanceledException after it finished.
Any idea?
```
var success = false;
using (var stream = new FileStream(data.FilePath, FileMode.Open, FileAccess.Read))
{
    try
    {
        success = await _seafileService.Session.UploadSingle(data.Library, data.SaveDirectory, data.SaveFileName, stream, OnUploadProgressChanged);
    }
    catch (Exception)
    {
        // ignored
    }
}
```

**Comment by renber** [comment]
I added an overload with a timeout parameter to the ISeafWebConnection interface. A different custom timeout can now be set when manually constructing a SeafHttpConnection instance.
Additionally, I have added the SendRequest method to SeafSession which has an optional parameter timeout. So, that every (custom) RequestMessage can be send with an individual timeout setting, if required.
